### ISSUE TITLE
Strict Standards

### ISSUE THREAD

**Issue by kostek00** [mihdan/ajax-edit-comments#4]
![static standards](https://cloud.githubusercontent.com/assets/6637173/3361418/3b3af9e8-fafe-11e3-9022-5249fbac1b46.png)
(Cutted from image not needed information.)

This is what I see when I'm on comments page in admin pane:
Strict Standards: Non-static method AECCore::can_edit() should not be called statically in /wp-content/plugins/wp-ajax-edit-comments/lib/class.filters.php on line 35

Strict Standards: Only variables should be assigned by reference in /www/wp-content/plugins/wp-ajax-edit-comments/lib/class.core.php on line 18

After that message there is comment content.

**Comment by mihdan** [comment]
https://wordpress.org/support/topic/bug-fix-proposal?replies=3

**Comment by mihdan** [comment]
Fixed
